version: '3.8'

services:
  avito-shop-service:
    build: .
    container_name: avito-assignment
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: avito_shop
    volumes:
      - ./migrations/1_init.up.sql:/docker-entrypoint-initdb.d/1_init.up.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d avito_shop"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal: