env: "dev"
db:
  addres: db
  port: 5432
  database: avito_shop
  user: postgres
  password: postgres
  schema: "public"
http_server: 
  addres: avito-shop-service
  port: 8080
  timeout: 5s
  idle_timeout: 60s
auth:
  secret: "avito_assignment"